-- Revert FORCE ROW LEVEL SECURITY
ALTER TABLE clusters NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cluster_registration_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cluster_heartbeats NO FORCE ROW LEVEL SECURITY;
