package provisioning

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"strings"
	"text/template"
	"time"
)

// BootstrapGenerator generates bootstrap commands for cluster registration.
type BootstrapGenerator struct {
	platformURL string
	agentImage  string
}

// NewBootstrapGenerator creates a new bootstrap generator.
func NewBootstrapGenerator(platformURL, agentImage string) *BootstrapGenerator {
	if platformURL == "" {
		platformURL = "https://api.bdsplatform.io"
	}
	if agentImage == "" {
		agentImage = "ghcr.io/bdsplatform/platform-agent:latest"
	}
	return &BootstrapGenerator{
		platformURL: platformURL,
		agentImage:  agentImage,
	}
}

// BootstrapCommand holds a bootstrap command with instructions.
type BootstrapCommand struct {
	// The one-liner command to run
	Command string `json:"command"`

	// Full YAML manifest (alternative to one-liner)
	Manifest string `json:"manifest"`

	// Human-readable instructions
	Instructions []string `json:"instructions"`

	// Token info
	Token     string    `json:"token"`
	TokenHash string    `json:"-"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// GenerateBootstrapToken generates a new bootstrap token.
func GenerateBootstrapToken() (token string, hash string, err error) {
	// Generate 32 random bytes
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", "", err
	}

	// Encode as base64
	token = base64.URLEncoding.EncodeToString(b)

	// Hash for storage
	h := sha256.Sum256([]byte(token))
	hash = hex.EncodeToString(h[:])

	return token, hash, nil
}

// HashToken hashes a token for storage/comparison.
func HashToken(token string) string {
	h := sha256.Sum256([]byte(token))
	return hex.EncodeToString(h[:])
}

// GenerateCommand generates a bootstrap command for cluster registration.
func (g *BootstrapGenerator) GenerateCommand(clusterName, token string, expiresAt time.Time) (*BootstrapCommand, error) {
	// Generate the one-liner
	cmd := fmt.Sprintf(
		`kubectl apply -f %s/v1/bootstrap/%s/manifest.yaml`,
		g.platformURL,
		token,
	)

	// Generate full manifest
	manifest, err := g.generateManifest(clusterName, token)
	if err != nil {
		return nil, err
	}

	return &BootstrapCommand{
		Command:  cmd,
		Manifest: manifest,
		Instructions: []string{
			"1. Ensure kubectl is configured to connect to your cluster",
			"2. Run the command below to install the BDS Platform agent",
			"3. The agent will automatically register with the platform",
			"4. You can monitor the progress in the platform dashboard",
		},
		Token:     token,
		TokenHash: HashToken(token),
		ExpiresAt: expiresAt,
	}, nil
}

func (g *BootstrapGenerator) generateManifest(clusterName, token string) (string, error) {
	data := struct {
		ClusterName string
		Token       string
		PlatformURL string
		AgentImage  string
	}{
		ClusterName: clusterName,
		Token:       token,
		PlatformURL: g.platformURL,
		AgentImage:  g.agentImage,
	}

	tmpl, err := template.New("manifest").Parse(agentManifestTemplate)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// Install step definitions
var DefaultInstallSteps = []StepInfo{
	{Number: 1, Name: "terraform_init", Description: "Initialize Terraform"},
	{Number: 2, Name: "terraform_plan", Description: "Plan infrastructure changes"},
	{Number: 3, Name: "terraform_apply", Description: "Apply infrastructure changes"},
	{Number: 4, Name: "wait_cluster", Description: "Wait for cluster to be ready"},
	{Number: 5, Name: "configure_kubectl", Description: "Configure kubectl access"},
	{Number: 6, Name: "install_agent", Description: "Install platform agent"},
	{Number: 7, Name: "agent_registration", Description: "Register agent with platform"},
	{Number: 8, Name: "verify_connection", Description: "Verify agent connection"},
}

// Agent manifest template
const agentManifestTemplate = `# BDS Platform Agent Installation
# Cluster: {{.ClusterName}}
# Generated by BDS Platform Provisioning Service

---
apiVersion: v1
kind: Namespace
metadata:
  name: bds-platform
  labels:
    app.kubernetes.io/name: bds-platform
    app.kubernetes.io/component: agent

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-agent-config
  namespace: bds-platform
type: Opaque
stringData:
  PLATFORM_URL: "{{.PlatformURL}}"
  BOOTSTRAP_TOKEN: "{{.Token}}"
  CLUSTER_NAME: "{{.ClusterName}}"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-agent
  namespace: bds-platform
  labels:
    app.kubernetes.io/name: platform-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-agent
  labels:
    app.kubernetes.io/name: platform-agent
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "configmaps", "secrets", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-agent
  labels:
    app.kubernetes.io/name: platform-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-agent
subjects:
  - kind: ServiceAccount
    name: platform-agent
    namespace: bds-platform

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-agent
  namespace: bds-platform
  labels:
    app.kubernetes.io/name: platform-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-agent
    spec:
      serviceAccountName: platform-agent
      containers:
        - name: agent
          image: {{.AgentImage}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: platform-agent-config
          env:
            - name: AGENT_MODE
              value: "bootstrap"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
`
