package provisioning

import (
	"bytes"
	"encoding/json"
	"fmt"
	"text/template"
)

// TerraformGenerator generates Terraform/OpenTofu configurations.
type TerraformGenerator struct {
	templates map[string]*template.Template
}

// NewTerraformGenerator creates a new Terraform generator.
func NewTerraformGenerator() *TerraformGenerator {
	g := &TerraformGenerator{
		templates: make(map[string]*template.Template),
	}

	// Parse templates
	g.templates[ProviderAWS] = template.Must(template.New("aws").Parse(awsTemplate))
	g.templates[ProviderAzure] = template.Must(template.New("azure").Parse(azureTemplate))
	g.templates[ProviderGCP] = template.Must(template.New("gcp").Parse(gcpTemplate))

	return g
}

// TerraformConfig holds the configuration for Terraform generation.
type TerraformConfig struct {
	ClusterName string
	Region      string
	K8sVersion  string
	NodePools   []NodePool
	Networking  *NetworkingConfig
	Addons      []ClusterAddon
	Tags        map[string]string

	// Provider-specific
	AWS   *AWSConfig
	Azure *AzureConfig
	GCP   *GCPConfig
}

// AWSConfig holds AWS-specific configuration.
type AWSConfig struct {
	VPCCidr         string
	AvailabilityZones []string
	EnableNATGateway bool
	PrivateCluster   bool
}

// AzureConfig holds Azure-specific configuration.
type AzureConfig struct {
	ResourceGroup    string
	VNetCidr         string
	DNSPrefix        string
	PrivateCluster   bool
}

// GCPConfig holds GCP-specific configuration.
type GCPConfig struct {
	ProjectID       string
	Network         string
	Subnetwork      string
	PrivateCluster  bool
	MasterIPv4CIDR  string
}

// GeneratedTerraform is the output of Terraform generation.
type GeneratedTerraform struct {
	MainTF     string                 `json:"mainTf"`
	VariablesTF string                `json:"variablesTf"`
	OutputsTF  string                 `json:"outputsTf"`
	TFVars     map[string]interface{} `json:"tfVars"`
}

// Generate generates Terraform configuration for the given provider.
func (g *TerraformGenerator) Generate(provider string, cfg TerraformConfig) (*GeneratedTerraform, error) {
	tmpl, ok := g.templates[provider]
	if !ok {
		return nil, fmt.Errorf("unsupported provider: %s", provider)
	}

	// Set defaults
	if cfg.K8sVersion == "" {
		cfg.K8sVersion = "1.28"
	}
	if cfg.Tags == nil {
		cfg.Tags = make(map[string]string)
	}
	cfg.Tags["managed-by"] = "bds-platform"

	// Generate main.tf
	var mainBuf bytes.Buffer
	if err := tmpl.Execute(&mainBuf, cfg); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	// Generate variables.tf
	variablesTF := g.generateVariables(provider, cfg)

	// Generate outputs.tf
	outputsTF := g.generateOutputs(provider)

	// Generate terraform.tfvars
	tfVars := g.generateTFVars(provider, cfg)

	return &GeneratedTerraform{
		MainTF:      mainBuf.String(),
		VariablesTF: variablesTF,
		OutputsTF:   outputsTF,
		TFVars:      tfVars,
	}, nil
}

func (g *TerraformGenerator) generateVariables(provider string, cfg TerraformConfig) string {
	switch provider {
	case ProviderAWS:
		return awsVariables
	case ProviderAzure:
		return azureVariables
	case ProviderGCP:
		return gcpVariables
	default:
		return ""
	}
}

func (g *TerraformGenerator) generateOutputs(provider string) string {
	switch provider {
	case ProviderAWS:
		return awsOutputs
	case ProviderAzure:
		return azureOutputs
	case ProviderGCP:
		return gcpOutputs
	default:
		return ""
	}
}

func (g *TerraformGenerator) generateTFVars(provider string, cfg TerraformConfig) map[string]interface{} {
	vars := map[string]interface{}{
		"cluster_name":    cfg.ClusterName,
		"region":          cfg.Region,
		"kubernetes_version": cfg.K8sVersion,
	}

	// Add node pools
	nodePoolsJSON, _ := json.Marshal(cfg.NodePools)
	vars["node_pools"] = string(nodePoolsJSON)

	// Add provider-specific vars
	switch provider {
	case ProviderAWS:
		if cfg.AWS != nil {
			vars["vpc_cidr"] = cfg.AWS.VPCCidr
			if len(cfg.AWS.AvailabilityZones) > 0 {
				vars["availability_zones"] = cfg.AWS.AvailabilityZones
			}
			vars["enable_nat_gateway"] = cfg.AWS.EnableNATGateway
			vars["private_cluster"] = cfg.AWS.PrivateCluster
		}
	case ProviderAzure:
		if cfg.Azure != nil {
			vars["resource_group"] = cfg.Azure.ResourceGroup
			vars["vnet_cidr"] = cfg.Azure.VNetCidr
			vars["dns_prefix"] = cfg.Azure.DNSPrefix
			vars["private_cluster"] = cfg.Azure.PrivateCluster
		}
	case ProviderGCP:
		if cfg.GCP != nil {
			vars["project_id"] = cfg.GCP.ProjectID
			vars["network"] = cfg.GCP.Network
			vars["subnetwork"] = cfg.GCP.Subnetwork
			vars["private_cluster"] = cfg.GCP.PrivateCluster
			vars["master_ipv4_cidr"] = cfg.GCP.MasterIPv4CIDR
		}
	}

	return vars
}

// AWS EKS Terraform template
const awsTemplate = `# BDS Platform - AWS EKS Cluster
# Generated by BDS Platform Provisioning Service

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

# Data sources
data "aws_availability_zones" "available" {
  state = "available"
}

# VPC
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "{{.ClusterName}}-vpc"
  cidr = var.vpc_cidr

  azs             = slice(data.aws_availability_zones.available.names, 0, 3)
  private_subnets = [for i, az in slice(data.aws_availability_zones.available.names, 0, 3) : cidrsubnet(var.vpc_cidr, 4, i)]
  public_subnets  = [for i, az in slice(data.aws_availability_zones.available.names, 0, 3) : cidrsubnet(var.vpc_cidr, 4, i + 3)]

  enable_nat_gateway     = var.enable_nat_gateway
  single_nat_gateway     = true
  enable_dns_hostnames   = true
  enable_dns_support     = true

  public_subnet_tags = {
    "kubernetes.io/role/elb" = "1"
  }

  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = "1"
  }

  tags = {
    "kubernetes.io/cluster/{{.ClusterName}}" = "shared"
    "managed-by" = "bds-platform"
  }
}

# EKS Cluster
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.0"

  cluster_name    = "{{.ClusterName}}"
  cluster_version = var.kubernetes_version

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  cluster_endpoint_public_access  = !var.private_cluster
  cluster_endpoint_private_access = true

  eks_managed_node_groups = {
{{- range $i, $pool := .NodePools }}
    {{$pool.Name}} = {
      name           = "{{$pool.Name}}"
      instance_types = ["{{$pool.MachineType}}"]
      
      min_size     = {{$pool.MinNodes}}
      max_size     = {{$pool.MaxNodes}}
      desired_size = {{$pool.DesiredNodes}}

      disk_size = {{if $pool.DiskSizeGB}}{{$pool.DiskSizeGB}}{{else}}50{{end}}

      labels = {
{{- range $k, $v := $pool.Labels }}
        "{{$k}}" = "{{$v}}"
{{- end }}
        "managed-by" = "bds-platform"
      }
    }
{{- end }}
  }

  tags = {
    "managed-by" = "bds-platform"
  }
}
`

const awsVariables = `# AWS EKS Variables
variable "region" {
  description = "AWS region"
  type        = string
}

variable "cluster_name" {
  description = "EKS cluster name"
  type        = string
}

variable "kubernetes_version" {
  description = "Kubernetes version"
  type        = string
  default     = "1.28"
}

variable "vpc_cidr" {
  description = "VPC CIDR block"
  type        = string
  default     = "10.0.0.0/16"
}

variable "enable_nat_gateway" {
  description = "Enable NAT gateway"
  type        = bool
  default     = true
}

variable "private_cluster" {
  description = "Make cluster private"
  type        = bool
  default     = false
}

variable "node_pools" {
  description = "Node pool configuration (JSON)"
  type        = string
  default     = "[]"
}
`

const awsOutputs = `# AWS EKS Outputs
output "cluster_endpoint" {
  description = "EKS cluster endpoint"
  value       = module.eks.cluster_endpoint
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded CA certificate"
  value       = module.eks.cluster_certificate_authority_data
  sensitive   = true
}

output "cluster_name" {
  description = "EKS cluster name"
  value       = module.eks.cluster_name
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = module.eks.cluster_arn
}

output "kubeconfig_command" {
  description = "Command to update kubeconfig"
  value       = "aws eks update-kubeconfig --region ${var.region} --name ${module.eks.cluster_name}"
}
`

// Azure AKS Terraform template
const azureTemplate = `# BDS Platform - Azure AKS Cluster
# Generated by BDS Platform Provisioning Service

terraform {
  required_version = ">= 1.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# Resource Group
resource "azurerm_resource_group" "main" {
  name     = var.resource_group
  location = var.region

  tags = {
    "managed-by" = "bds-platform"
  }
}

# Virtual Network
resource "azurerm_virtual_network" "main" {
  name                = "{{.ClusterName}}-vnet"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space       = [var.vnet_cidr]

  tags = {
    "managed-by" = "bds-platform"
  }
}

resource "azurerm_subnet" "main" {
  name                 = "{{.ClusterName}}-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = [cidrsubnet(var.vnet_cidr, 8, 0)]
}

# AKS Cluster
resource "azurerm_kubernetes_cluster" "main" {
  name                = "{{.ClusterName}}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = var.dns_prefix
  kubernetes_version  = var.kubernetes_version

  private_cluster_enabled = var.private_cluster

{{- range $i, $pool := .NodePools }}
{{- if eq $i 0 }}
  default_node_pool {
    name           = "{{$pool.Name}}"
    vm_size        = "{{$pool.MachineType}}"
    min_count      = {{$pool.MinNodes}}
    max_count      = {{$pool.MaxNodes}}
    node_count     = {{$pool.DesiredNodes}}
    os_disk_size_gb = {{if $pool.DiskSizeGB}}{{$pool.DiskSizeGB}}{{else}}50{{end}}
    vnet_subnet_id = azurerm_subnet.main.id
    enable_auto_scaling = true

    node_labels = {
{{- range $k, $v := $pool.Labels }}
      "{{$k}}" = "{{$v}}"
{{- end }}
      "managed-by" = "bds-platform"
    }
  }
{{- end }}
{{- end }}

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    network_plugin    = "azure"
    load_balancer_sku = "standard"
    network_policy    = "azure"
  }

  tags = {
    "managed-by" = "bds-platform"
  }
}

{{- range $i, $pool := .NodePools }}
{{- if gt $i 0 }}
resource "azurerm_kubernetes_cluster_node_pool" "{{$pool.Name}}" {
  name                  = "{{$pool.Name}}"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.main.id
  vm_size               = "{{$pool.MachineType}}"
  min_count             = {{$pool.MinNodes}}
  max_count             = {{$pool.MaxNodes}}
  node_count            = {{$pool.DesiredNodes}}
  os_disk_size_gb       = {{if $pool.DiskSizeGB}}{{$pool.DiskSizeGB}}{{else}}50{{end}}
  vnet_subnet_id        = azurerm_subnet.main.id
  enable_auto_scaling   = true

  node_labels = {
{{- range $k, $v := $pool.Labels }}
    "{{$k}}" = "{{$v}}"
{{- end }}
    "managed-by" = "bds-platform"
  }
}
{{- end }}
{{- end }}
`

const azureVariables = `# Azure AKS Variables
variable "region" {
  description = "Azure region"
  type        = string
}

variable "cluster_name" {
  description = "AKS cluster name"
  type        = string
}

variable "resource_group" {
  description = "Azure resource group name"
  type        = string
}

variable "kubernetes_version" {
  description = "Kubernetes version"
  type        = string
  default     = "1.28"
}

variable "vnet_cidr" {
  description = "Virtual network CIDR"
  type        = string
  default     = "10.0.0.0/16"
}

variable "dns_prefix" {
  description = "DNS prefix for the cluster"
  type        = string
}

variable "private_cluster" {
  description = "Make cluster private"
  type        = bool
  default     = false
}

variable "node_pools" {
  description = "Node pool configuration (JSON)"
  type        = string
  default     = "[]"
}
`

const azureOutputs = `# Azure AKS Outputs
output "cluster_id" {
  description = "AKS cluster ID"
  value       = azurerm_kubernetes_cluster.main.id
}

output "cluster_fqdn" {
  description = "AKS cluster FQDN"
  value       = azurerm_kubernetes_cluster.main.fqdn
}

output "kube_config" {
  description = "Kubeconfig"
  value       = azurerm_kubernetes_cluster.main.kube_config_raw
  sensitive   = true
}

output "kubeconfig_command" {
  description = "Command to get kubeconfig"
  value       = "az aks get-credentials --resource-group ${var.resource_group} --name ${azurerm_kubernetes_cluster.main.name}"
}
`

// GCP GKE Terraform template
const gcpTemplate = `# BDS Platform - GCP GKE Cluster
# Generated by BDS Platform Provisioning Service

terraform {
  required_version = ">= 1.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# VPC Network
resource "google_compute_network" "main" {
  name                    = "{{.ClusterName}}-vpc"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "main" {
  name          = "{{.ClusterName}}-subnet"
  ip_cidr_range = "10.0.0.0/20"
  region        = var.region
  network       = google_compute_network.main.id

  secondary_ip_range {
    range_name    = "pods"
    ip_cidr_range = "10.1.0.0/16"
  }

  secondary_ip_range {
    range_name    = "services"
    ip_cidr_range = "10.2.0.0/20"
  }
}

# GKE Cluster
resource "google_container_cluster" "main" {
  name     = "{{.ClusterName}}"
  location = var.region

  network    = google_compute_network.main.name
  subnetwork = google_compute_subnetwork.main.name

  # Autopilot mode or Standard
  enable_autopilot = false

  # We can't create a cluster with no node pool, but we want to use
  # separately managed node pools. So we create the smallest possible
  # default node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 1

  min_master_version = var.kubernetes_version

  ip_allocation_policy {
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }

  private_cluster_config {
    enable_private_nodes    = var.private_cluster
    enable_private_endpoint = false
    master_ipv4_cidr_block  = var.master_ipv4_cidr
  }

  resource_labels = {
    "managed-by" = "bds-platform"
  }
}

{{- range $i, $pool := .NodePools }}
resource "google_container_node_pool" "{{$pool.Name}}" {
  name       = "{{$pool.Name}}"
  location   = var.region
  cluster    = google_container_cluster.main.name
  
  initial_node_count = {{$pool.DesiredNodes}}

  autoscaling {
    min_node_count = {{$pool.MinNodes}}
    max_node_count = {{$pool.MaxNodes}}
  }

  node_config {
    machine_type = "{{$pool.MachineType}}"
    disk_size_gb = {{if $pool.DiskSizeGB}}{{$pool.DiskSizeGB}}{{else}}50{{end}}
    disk_type    = "{{if $pool.DiskType}}{{$pool.DiskType}}{{else}}pd-standard{{end}}"
    preemptible  = {{$pool.Preemptible}}

    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]

    labels = {
{{- range $k, $v := $pool.Labels }}
      "{{$k}}" = "{{$v}}"
{{- end }}
      "managed-by" = "bds-platform"
    }

    metadata = {
      disable-legacy-endpoints = "true"
    }
  }
}
{{- end }}
`

const gcpVariables = `# GCP GKE Variables
variable "project_id" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region"
  type        = string
}

variable "cluster_name" {
  description = "GKE cluster name"
  type        = string
}

variable "kubernetes_version" {
  description = "Kubernetes version"
  type        = string
  default     = "1.28"
}

variable "network" {
  description = "VPC network name"
  type        = string
  default     = ""
}

variable "subnetwork" {
  description = "VPC subnetwork name"
  type        = string
  default     = ""
}

variable "private_cluster" {
  description = "Make cluster private"
  type        = bool
  default     = false
}

variable "master_ipv4_cidr" {
  description = "Master IPv4 CIDR for private cluster"
  type        = string
  default     = "172.16.0.0/28"
}

variable "node_pools" {
  description = "Node pool configuration (JSON)"
  type        = string
  default     = "[]"
}
`

const gcpOutputs = `# GCP GKE Outputs
output "cluster_endpoint" {
  description = "GKE cluster endpoint"
  value       = google_container_cluster.main.endpoint
}

output "cluster_ca_certificate" {
  description = "GKE cluster CA certificate"
  value       = google_container_cluster.main.master_auth[0].cluster_ca_certificate
  sensitive   = true
}

output "cluster_name" {
  description = "GKE cluster name"
  value       = google_container_cluster.main.name
}

output "kubeconfig_command" {
  description = "Command to get kubeconfig"
  value       = "gcloud container clusters get-credentials ${google_container_cluster.main.name} --region ${var.region} --project ${var.project_id}"
}
`
